import 'dart:io';

/// Tiny Markdown report builder shared by the Phase 2 showcase scripts.
///
/// Pure `dart:io` only — no Flutter, no model. Each showcase writes a
/// human-readable `.md` under `docs/reports/showcase/`.
class MarkdownReport {
  final StringBuffer _b = StringBuffer();

  MarkdownReport(String title, {String? subtitle}) {
    _b
      ..writeln('# $title')
      ..writeln();
    if (subtitle != null) {
      _b
        ..writeln('_${subtitle}_')
        ..writeln();
    }
    _b
      ..writeln(
          '> Generated by `tools/showcase/` — a headless run of the Phase 2 '
          'deterministic core (no Flutter, no model).')
      ..writeln();
  }

  void h2(String s) => _b
    ..writeln()
    ..writeln('## $s')
    ..writeln();

  void h3(String s) => _b
    ..writeln()
    ..writeln('### $s')
    ..writeln();

  void p(String s) => _b
    ..writeln(s)
    ..writeln();

  void bullet(String s) => _b.writeln('- $s');

  void endBullets() => _b.writeln();

  void callout(String s) => _b
    ..writeln('> $s')
    ..writeln();

  void code(String s, {String lang = 'text'}) => _b
    ..writeln('```$lang')
    ..writeln(s)
    ..writeln('```')
    ..writeln();

  void table(List<String> headers, List<List<String>> rows) {
    _b.writeln('| ${headers.join(' | ')} |');
    _b.writeln('| ${headers.map((_) => '---').join(' | ')} |');
    for (final row in rows) {
      _b.writeln('| ${row.map(_escape).join(' | ')} |');
    }
    _b.writeln();
  }

  static String _escape(String s) => s.replaceAll('|', r'\|');

  /// ✅ / ❌ marker for a boolean assertion.
  static String ok(bool value) => value ? '✅' : '❌';

  String toMarkdown() => _b.toString();

  /// Writes the report to [path] (relative to cwd), creating dirs as needed.
  void writeTo(String path) {
    final file = File(path);
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(toMarkdown());
    stdout.writeln('  wrote $path');
  }
}

/// Loads the two committed sample manifests, returning (id → manifest bytes).
/// Kept here so every showcase resolves cases the same way.
const String showcaseOutputDir = 'docs/reports/showcase';
