name: psychosims
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  psyconfig:
    path: ../config
  psychemas:
    path: ../packages/psychemas
  psycore:
    path: ../packages/psycore

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
